development: 
  adapter: postgresql
  pool: 5
  encoding: UTF-8
  database: bbw_production # should be bbw_development
  host: localhost
  username: postgres
  password: postgres

test: 
  adapter: postgresql
  pool: 5
  encoding: UTF-8
  database: bbw_test
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  pool: 5
  encoding: UTF-8
  database: bbw_production
  host: localhost
  username: postgres
  password: 